env:
  local:
    server:
      port: 8080
    database:
      name: demo
      host: localhost
      port: 5432
      user: postgres
      password: postgres

  testing:
    server:
      port: 8080
    database:
      name: demo
      host: localhost
      port: 5432
      user: postgres
      password: postgres

  production:
    server:
      port: 8080
    database:
      name: demo
      host: localhost
      port: 5432
      user: postgres
      password: postgres